### PR TITLE
Matrix and Nexus and Omega

### PR DESCRIPTION
**Pull request by teletcl**
I made changes to file "Textures.xbt" (from "Kodi/addons/skin.quartz/media" folder) - added missing logos and fixed some oldest, make them look visually better.
Could You include it for next update?

### CODE REVIEW

**Comment by teletcl** [comment]
Hello again.



I also modified some files from the 16x9 folder to make better use of the space of the screen, and in some cases the texts had to be shifted horizontally because they overlapped after translation (eg. Polish lang). 
Also added ability to use **AutoCompletion for virtual keyboard script** (from official Kodi Add-on Repository) and added some missing keys for virtual keyboard. Now skin can show change log (if exists) for addons; in video addons their settings is accessible from side menu.



The file matches to Matrix and Nexus versions, and possibly also Leila.

I tested for several days, on PC and AndroidTV, to find as many bugs as possible. But You'll probably have to test it yourself, to see what it looks like. Just unpack files and replace with originals.

From SOME badges I deleted border around them, because in my opinion they look betters without. Everything looks very nice now. I hope you'll like too.


Kind regards

**Comment by teletcl** [comment]
I've made temporary fix to work with Kodi 21 Omega.
[Kodi21OmegaFIX.zip](https://github.com/nonJon/skin.quartz/files/15001524/Kodi21OmegaFIX.zip)

**Comment by teletcl** [comment]
Installer, complete version:
[skin.quartz_Kodi21Omega - INSTALLER.zip](https://github.com/nonJon/skin.quartz/files/15020860/skin.quartz_Kodi21Omega.-.INSTALLER.zip)

**Comment by nonJon** [comment]
I do not accept pull requests.  Feature requests, sans code, should be made via the quartz sub-forum.  That said, I will save you the trouble per these specific changes.  They will not be integrated into mainline quartz.  

Furthermore, publishing unsanctioned mods in this venue is a no no.  I have removed all comments containing zip archives.

**Pull request closed without merging**
